name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.12'
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: "latest"  # Ensure Miniconda is installed

      - name: Install Mamba
        run: |
          echo "Installing Mamba"
          conda install -n base -c conda-forge mamba
      
      - name: Create Mamba environment
        run: |
          echo "Creating Mamba environment"
          mamba create --name splineops_env python=3.12 -c conda-forge
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          mamba run -n splineops_env mamba install numpy scipy matplotlib pooch IPython sphinx sphinx-gallery sphinx-prompt sphinx-copybutton sphinx-remove-toctrees pydata-sphinx-theme myst-parser -c conda-forge
          mamba run -n splineops_env pip install -e .[docs]
      
      - name: Build documentation
        run: |
          echo "Building documentation"
          mamba run -n splineops_env make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: splineops/splineops.github.io
          publish_branch: main
          publish_dir: docs/_build/html